sudo: false
dist: trusty
language: python
python:
    - 2.7
    - 3.5
    - 3.6
before_install:
    - pip install -U pip
    - pip install -U setuptools
install:
    - pip install -r requirements-dev.txt
    - pip install -e .
script:
    - pytest
    - flake8 --ignore E402 .
after_success:
    - coveralls
cache:
    - pip
    - apt
